sources:
  npm: true
- name: Setup Python
  uses: actions/setup-python@v6.0.0
allowed:
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - mit
  - cc0-1.0
  - unlicense
  - 0bsd

reviewed:
  npm:
