---
name: 'Setup Python'
description: 'Set up a specific version of Python and add the command-line tools to the PATH.'
author: 'GitHub'
inputs:
  python-version:
    description: "Version range or exact version of a Python version to use, using SemVer's version range syntax."
    default: '3.x'
  cache:
    description: 'Used to specify a package manager for caching in the default directory. Supported values: pip, pipenv, poetry.'
    required: false
  architecture:
    description: 'The target architecture (x86, x64) of the Python interpreter.'
  token:
    description: Used to pull python distributions from actions/python-versions. Since there's a default, this is typically not supplied by the user.
    default: ${{ github.token }}
  cache-dependency-path:
    description: 'Used to specify the path to dependency files. Supports wildcards or a list of file names for caching multiple dependencies.'
outputs:
  python-version:
    description: "The installed python version. Useful when given a version range as input."
  cache-hit:
    description: 'A boolean value to indicate a cache entry was found'
runs:
  using: 'node16'
  main: 'dist/setup/index.js'
  post: 'dist/cache-save/index.js'
  post-if: success()
branding:
  icon: 'code'
  color: 'yellow'
