---
name: 'Setup Python'
description: 'Set up a specific version of Python and add the command-line tools to the PATH.'
author: 'GitHub'
inputs:
  python-version:
    description: "Version range or exact version of Python to use, using SemVer's version range syntax. Reads from .python-version if unset."
  python-version-file:
    description: "File containing the Python version to use. Example: .python-version"
  cache:
    description: 'Used to specify a package manager for caching in the default directory. Supported values: pip, pipenv, poetry.'
    required: false
  architecture:
    description: 'The target architecture (x86, x64) of the Python interpreter.'
  token:
    description: The token used to authenticate when to fetching Python distributions from https://github.com/actions/python-versions. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    default: ${{ github.token }}
  cache-dependency-path:
    description: 'Used to specify the path to dependency files. Supports wildcards or a list of file names for caching multiple dependencies.'
outputs:
  python-version:
    description: "The installed python version. Useful when given a version range as input."
  cache-hit:
    description: 'A boolean value to indicate a cache entry was found'
  python-path:
    description: "The absolute path to the Python executable."
runs:
  using: 'node16'
  main: 'dist/setup/index.js'
  post: 'dist/cache-save/index.js'
  post-if: success()
branding:
  icon: 'code'
  color: 'yellow'
