name: 'Setup Python'
description: 'Set up a specific version of Python and add the command-line tools to the PATH'
author: 'GitHub'
inputs:
  python-version:
    description: 'Version range or exact version of a Python version to use, using semvers version range syntax.'
    default: '3.x'
  architecture:
    description: 'The target architecture (x86, x64) of the Python interpreter.'
    default: 'x64'
runs:
  using: 'node12'
  main: 'lib/setup-python.js'
