name: Python CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13' # Set your specific Python version here
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-test.txt

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      # Add more steps here, like running your tests
      - name: Run tests
        run: |
          pytest # Replace with your test command